services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      # CÃ³digo local
      - .:/app
      # Montar socket de docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Montar x11
      - /tmp/.X11-unix:/tmp/.X11-unix
    # Corre 'go mod tidy'
    command: sh -c "go mod tidy && /go/bin/air"
    privileged: true
    network_mode: "host"
    pid: "host"